### ISSUE TITLE
GC free Power Measuring extraction 

### ISSUE THREAD

**Issue by franz1981** [metacosm/quarkus-power#14]
This is an unverified proposal, assuming the content of the rapl file to be:
- ASCII encoded
- at least of  `String.valueOf(Long.MAX_VALUE).length()`, but TBH could be changed easily 

```java
 private static MappedByteBuffer mapRaplFile(Path file) throws IOException {
      try (var channel = FileChannel.open(file, StandardOpenOption.READ)) {
         return channel.map(FileChannel.MapMode.READ_ONLY, 0, String.valueOf(Long.MAX_VALUE).length());
      }
   }

   private static long extractPowerMeasure(MappedByteBuffer raplBuffer) {
        long value = 0;
        // will work even better if we can hard code as a static final const the length, in case won't change or is defined by spec
        for (int i = 0; i < raplBuffer.capacity(); i++) {
             byte digit = raplBuffer.get(i);
             if (digit >= '0' && digit <= '9') {
               value = value * 10 + (digit - '0');
             } else {
                if (digit == ' ') {
                     return value;
                }
               // Invalid character; handle accordingly or throw an exception
               throw new NumberFormatException("Invalid character in input");
             }
        }
        return value;
   }
```

the parsing could be made way faster by using lookup tables + masking and by batch reading out of the buffer (in 8-bytes strides), but in this form should be already way faster than the existing code (if it works what i've written here :P )

About the "it works?" part, I'm just concern of memory mapping and if we can expect the data in the file to be updated correctly by the kernel in "one go", atomically, or we need some form of control/checkum, to be sure of it (IDK).

**Comment by franz1981** [comment]
The stop at whitespace part, is up to you, I didn't implemented it to trim before or after, but you now have a toy to play with :P

**Comment by metacosm** [comment]
I believe this is now fixed with https://github.com/metacosm/quarkus-power/blob/main/runtime/src/main/java/io/quarkiverse/power/runtime/sensors/linux/rapl/IntelRAPLSensor.java#L25
